"""empty message

Revision ID: 45d885ee4d84
Revises: 
Create Date: 2022-06-27 17:39:48.436245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d885ee4d84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.String(length=30), nullable=False),
    sa.Column('jam', sa.String(length=10), nullable=False),
    sa.Column('kota', sa.Integer(), nullable=True),
    sa.Column('tona', sa.Integer(), nullable=True),
    sa.Column('kolongan', sa.Integer(), nullable=True),
    sa.Column('lesabe', sa.Integer(), nullable=True),
    sa.Column('tamako', sa.Integer(), nullable=True),
    sa.Column('mainlinepetta', sa.Integer(), nullable=True),
    sa.Column('pettakota', sa.Integer(), nullable=True),
    sa.Column('mainlinetahuna', sa.Integer(), nullable=True),
    sa.Column('kendahe', sa.Integer(), nullable=True),
    sa.Column('bowongkulu', sa.Integer(), nullable=True),
    sa.Column('kotatamako', sa.Integer(), nullable=True),
    sa.Column('lapango', sa.Integer(), nullable=True),
    sa.Column('tahuna', sa.Integer(), nullable=True),
    sa.Column('salurang', sa.Integer(), nullable=True),
    sa.Column('pintareng', sa.Integer(), nullable=True),
    sa.Column('tahunaincome', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feeder')
    # ### end Alembic commands ###
