"""empty message

Revision ID: a1e44569d043
Revises: ece896539253
Create Date: 2022-06-29 23:52:24.310213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1e44569d043'
down_revision = 'ece896539253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mesin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit', sa.String(length=5), nullable=False),
    sa.Column('nama_mesin', sa.String(length=20), nullable=False),
    sa.Column('daya_mampu', sa.Integer(), nullable=False),
    sa.Column('is_sewa', sa.Boolean(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mesin')
    # ### end Alembic commands ###
