"""empty message

Revision ID: ece896539253
Revises: f8528dadf4f1
Create Date: 2022-06-29 17:39:14.184884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece896539253'
down_revision = 'f8528dadf4f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_unit', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mesin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('unit', sa.String(length=5), nullable=False),
    sa.Column('nama_mesin', sa.String(length=20), nullable=False),
    sa.Column('daya_mampu', sa.String(length=20), nullable=False),
    sa.Column('is_sewa', sa.Boolean(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mesin')
    op.drop_table('unit')
    # ### end Alembic commands ###
