"""empty message

Revision ID: f8528dadf4f1
Revises: a6f2b21d46c8
Create Date: 2022-06-27 18:03:10.378374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8528dadf4f1'
down_revision = 'a6f2b21d46c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeder', 'pltd_tahuna')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeder', sa.Column('pltd_tahuna', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
